database:
  dev: /data/grilvum_database_dev.db
  release: /data/grilvum_database.db
extensions:
  dev:
    - addons.admin_commands
    - addons.error_handling
    - addons.update_commands
    - addons.branch_commands
    - extensions.party_funds
    - extensions.bag_of_holding
  release:
    - addons.admin_commands
    - addons.error_handling
    - addons.update_commands
    - extensions.party_funds
    - extensions.bag_of_holding
prefix: 
  dev: "?"
  release: "!"
playing: 
  dev: "in development | {prefix}help"
  release: "party packmule | {prefix}help"
